"""
FollowUpQuestion model – AI-generated clarification questions for requirements.

Phase 7: generated by GroqService, answered by user.
"""
from sqlalchemy import Column, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from app.models.base_model import BaseModel


class FollowUpQuestion(BaseModel):
    """One follow-up question tied to a meeting (optionally to a specific requirement)."""

    __tablename__ = "follow_up_questions"

    # ── Ownership ──────────────────────────────────────────────────
    meeting_id = Column(Integer, ForeignKey("meetings.id"), nullable=False, index=True)

    # requirement_id is nullable — some questions apply to the meeting as a whole
    requirement_id = Column(
        Integer,
        ForeignKey("requirement_candidates.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    # ── Question content ──────────────────────────────────────────
    question = Column(Text, nullable=False)
    reason    = Column(Text, nullable=True)   # why this question was generated
    priority  = Column(String(20), default="MEDIUM", nullable=False)
    # HIGH | MEDIUM | LOW

    # ── Lifecycle ─────────────────────────────────────────────────
    status = Column(String(20), default="OPEN", nullable=False, index=True)
    # OPEN | ANSWERED | SKIPPED

    answer = Column(Text, nullable=True)      # user-supplied answer

    # ── Relationships ─────────────────────────────────────────────
    meeting     = relationship("Meeting")
    requirement = relationship("RequirementCandidate", foreign_keys=[requirement_id])

    def __repr__(self) -> str:
        return (
            f"<FollowUpQuestion id={self.id} "
            f"meeting={self.meeting_id} status={self.status!r}>"
        )
