"""
brd_template.py – BRD DOCX document builder using python-docx.

Takes a validated BRDContent object + meeting metadata and produces
a professional Word document.  The LLM generates content; this module
structures it into a formatted DOCX file.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

from app.brd.schemas.brd_schema import BRDContent
from app.brd.utils.document_utils import (
    add_heading, add_paragraph, add_bullet_list,
    add_table_section, add_page_break, set_footer,
)


def build_brd_document(
    brd_content: BRDContent,
    meeting_title: str,
    project_name: str,
    meeting_date: str,
    participants: str,
    model_name: str,
    output_path: Path,
) -> Path:
    """
    Build and save a DOCX BRD file.

    Args:
        brd_content:   Validated BRDContent from LLM.
        meeting_title: Title of the meeting.
        project_name:  Project name.
        meeting_date:  Meeting date string.
        participants:  Comma-separated participant names.
        model_name:    LLM model name for document footer.
        output_path:   Full path where the DOCX will be saved.

    Returns:
        Path to the saved DOCX file.
    """
    doc = Document()

    # ── Page margins ─────────────────────────────────────────────
    for section in doc.sections:
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin   = Inches(1.2)
        section.right_margin  = Inches(1.2)

    # ═══════════════════════════════════════════════════
    # 1. Cover Page
    # ═══════════════════════════════════════════════════
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run("BUSINESS REQUIREMENT DOCUMENT")
    run.bold = True
    run.font.size = Pt(22)

    doc.add_paragraph()
    proj_para = doc.add_paragraph()
    proj_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run2 = proj_para.add_run(project_name or meeting_title)
    run2.bold = True
    run2.font.size = Pt(16)

    doc.add_paragraph()
    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    generated_at = datetime.now(timezone.utc).strftime("%B %d, %Y")
    meta_para.add_run(f"Generated: {generated_at}\nMeeting: {meeting_date or 'Not specified'}")

    add_page_break(doc)

    # ═══════════════════════════════════════════════════
    # 2. Document Information
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Document Information", level=1)
    add_table_section(
        doc,
        headers=["Field", "Value"],
        rows=[
            ["Document Title",    f"BRD – {meeting_title}"],
            ["Project Name",      project_name or "Not specified"],
            ["Meeting Date",      meeting_date or "Not specified"],
            ["Participants",      participants or "Not specified"],
            ["Generated By",      f"ReqAI ({model_name})"],
            ["Generated On",      generated_at],
            ["Status",            "Draft"],
        ],
    )
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 3. Project Overview
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Project Overview", level=1)
    add_paragraph(doc, brd_content.project_overview or "Not specified")
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 4. Business Objective
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Business Objective", level=1)
    add_paragraph(doc, brd_content.business_objective or "Not specified")
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 5. Project Scope
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Project Scope", level=1)
    add_heading(doc, "In Scope", level=2)
    add_bullet_list(doc, brd_content.scope.in_scope)
    add_heading(doc, "Out of Scope", level=2)
    add_bullet_list(doc, brd_content.scope.out_of_scope)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 6. Stakeholders
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Stakeholders", level=1)
    add_bullet_list(doc, brd_content.stakeholders)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 7. User Roles
    # ═══════════════════════════════════════════════════
    add_heading(doc, "User Roles", level=1)
    add_bullet_list(doc, brd_content.user_roles)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 8. Functional Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Functional Requirements", level=1)
    if brd_content.functional_requirements:
        rows = [
            [r.id or f"FR-{i+1:02d}", r.description, r.priority]
            for i, r in enumerate(brd_content.functional_requirements)
        ]
        add_table_section(doc, ["ID", "Description", "Priority"], rows)
    else:
        add_paragraph(doc, "Not specified")
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 9. Non-Functional Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Non-Functional Requirements", level=1)
    if brd_content.non_functional_requirements:
        rows = [
            [r.id or f"NFR-{i+1:02d}", r.category or "", r.description]
            for i, r in enumerate(brd_content.non_functional_requirements)
        ]
        add_table_section(doc, ["ID", "Category", "Description"], rows)
    else:
        add_paragraph(doc, "Not specified")
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 10. Security Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Security Requirements", level=1)
    add_bullet_list(doc, brd_content.security_requirements)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 11. Performance Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Performance Requirements", level=1)
    add_bullet_list(doc, brd_content.performance_requirements)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 12. Usability Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Usability Requirements", level=1)
    add_bullet_list(doc, brd_content.usability_requirements)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 13. Business Rules
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Business Rules", level=1)
    add_bullet_list(doc, brd_content.business_rules)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 14. Integration Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Integration Requirements", level=1)
    add_bullet_list(doc, brd_content.integration_requirements)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 15. Data / Database Requirements
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Data / Database Requirements", level=1)
    add_bullet_list(doc, brd_content.data_requirements)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 16. Assumptions
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Assumptions", level=1)
    add_bullet_list(doc, brd_content.assumptions)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 17. Constraints
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Constraints", level=1)
    add_bullet_list(doc, brd_content.constraints)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 18. Dependencies
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Dependencies", level=1)
    add_bullet_list(doc, brd_content.dependencies)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 19. Risks
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Risks", level=1)
    if brd_content.risks:
        rows = [
            [r.risk, r.impact, r.mitigation or "Not specified"]
            for r in brd_content.risks
        ]
        add_table_section(doc, ["Risk", "Impact", "Mitigation"], rows)
    else:
        add_paragraph(doc, "Not specified")
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 20. Acceptance Criteria
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Acceptance Criteria", level=1)
    add_bullet_list(doc, brd_content.acceptance_criteria)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 21. Open Questions
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Open Questions", level=1)
    add_bullet_list(doc, brd_content.open_questions)
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 22. Meeting Summary
    # ═══════════════════════════════════════════════════
    add_heading(doc, "Meeting Summary", level=1)
    add_paragraph(doc, brd_content.meeting_summary or "Not specified")
    doc.add_paragraph()

    # ═══════════════════════════════════════════════════
    # 23. Approval Section
    # ═══════════════════════════════════════════════════
    add_page_break(doc)
    add_heading(doc, "Approval", level=1)
    approval_rows = [
        ["Project Manager", "", ""],
        ["Business Analyst", "", ""],
        ["Technical Lead", "", ""],
        ["Client Representative", "", ""],
    ]
    add_table_section(doc, ["Role", "Name", "Signature / Date"], approval_rows)

    # ── Footer ────────────────────────────────────────
    set_footer(
        doc,
        f"ReqAI BRD – {project_name or meeting_title} – Generated by {model_name} – DRAFT",
    )

    # ── Save ─────────────────────────────────────────
    output_path.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(output_path))
    return output_path
